// Curated food database — macros per 100g (cal in kcal, protein/carbs/fat in g)
// serving: { weight, label } — weight in grams per 1 piece; shown as piece-count input in UI
export const FOODS = [
  // ── Indian Breakfast ─────────────────────────────────────────────────────────
  { id: 'poha',             name: 'Poha',                    category: 'Indian Breakfast', cal: 120, protein: 2.5, carbs: 24, fat: 1.5 },
  { id: 'upma',             name: 'Upma',                    category: 'Indian Breakfast', cal: 130, protein: 3,   carbs: 22, fat: 3.5 },
  { id: 'plain-paratha',    name: 'Paratha (Plain)',          category: 'Indian Breakfast', cal: 297, protein: 8,   carbs: 47, fat: 9,   serving: { weight: 80,  label: 'paratha'  } },
  { id: 'aloo-paratha',     name: 'Aloo Paratha',            category: 'Indian Breakfast', cal: 260, protein: 6,   carbs: 42, fat: 8,   serving: { weight: 100, label: 'paratha'  } },
  { id: 'methi-paratha',    name: 'Methi Paratha',           category: 'Indian Breakfast', cal: 275, protein: 7,   carbs: 43, fat: 9,   serving: { weight: 80,  label: 'paratha'  } },
  { id: 'puri',             name: 'Puri',                    category: 'Indian Breakfast', cal: 335, protein: 8,   carbs: 48, fat: 13,  serving: { weight: 40,  label: 'puri'     } },
  { id: 'bhatura',          name: 'Bhatura',                 category: 'Indian Breakfast', cal: 350, protein: 8,   carbs: 50, fat: 13,  serving: { weight: 100, label: 'bhatura'  } },
  { id: 'chole-bhature',    name: 'Chole Bhature',           category: 'Indian Breakfast', cal: 295, protein: 9,   carbs: 42, fat: 11 },
  { id: 'puri-sabji',       name: 'Puri with Sabzi',         category: 'Indian Breakfast', cal: 280, protein: 7,   carbs: 40, fat: 11 },
  { id: 'aloo-puri',        name: 'Aloo Puri',               category: 'Indian Breakfast', cal: 290, protein: 6,   carbs: 42, fat: 11 },
  { id: 'sabudana-khichdi', name: 'Sabudana Khichdi',        category: 'Indian Breakfast', cal: 205, protein: 3,   carbs: 38, fat: 5   },
  { id: 'besan-chilla',     name: 'Besan Chilla',            category: 'Indian Breakfast', cal: 185, protein: 9,   carbs: 22, fat: 7,   serving: { weight: 80,  label: 'chilla'   } },
  { id: 'pesarattu',        name: 'Pesarattu',               category: 'Indian Breakfast', cal: 160, protein: 8,   carbs: 26, fat: 3,   serving: { weight: 80,  label: 'piece'    } },

  // ── Roti & Bread ─────────────────────────────────────────────────────────────
  { id: 'roti',             name: 'Roti / Chapati',          category: 'Roti & Bread',     cal: 297, protein: 9,   carbs: 55, fat: 4,   serving: { weight: 30,  label: 'roti'     } },
  { id: 'wheat-roti',       name: 'Whole Wheat Roti',        category: 'Roti & Bread',     cal: 280, protein: 9,   carbs: 52, fat: 3.5, serving: { weight: 30,  label: 'roti'     } },
  { id: 'naan',             name: 'Naan',                    category: 'Roti & Bread',     cal: 310, protein: 9,   carbs: 53, fat: 7,   serving: { weight: 90,  label: 'naan'     } },
  { id: 'garlic-naan',      name: 'Garlic Naan',             category: 'Roti & Bread',     cal: 330, protein: 9,   carbs: 54, fat: 9,   serving: { weight: 90,  label: 'naan'     } },
  { id: 'kulcha',           name: 'Kulcha',                  category: 'Roti & Bread',     cal: 290, protein: 8,   carbs: 52, fat: 6,   serving: { weight: 90,  label: 'kulcha'   } },
  { id: 'tandoori-roti',    name: 'Tandoori Roti',           category: 'Roti & Bread',     cal: 280, protein: 9,   carbs: 52, fat: 4,   serving: { weight: 40,  label: 'roti'     } },
  { id: 'missi-roti',       name: 'Missi Roti',              category: 'Roti & Bread',     cal: 280, protein: 10,  carbs: 48, fat: 6,   serving: { weight: 40,  label: 'roti'     } },
  { id: 'rumali-roti',      name: 'Rumali Roti',             category: 'Roti & Bread',     cal: 265, protein: 8,   carbs: 50, fat: 4,   serving: { weight: 50,  label: 'roti'     } },

  // ── Rice ─────────────────────────────────────────────────────────────────────
  { id: 'white-rice',       name: 'White Rice (cooked)',     category: 'Rice',             cal: 130, protein: 3,   carbs: 28, fat: 0.3 },
  { id: 'basmati-rice',     name: 'Basmati Rice (cooked)',   category: 'Rice',             cal: 130, protein: 3,   carbs: 28, fat: 0.2 },
  { id: 'brown-rice',       name: 'Brown Rice (cooked)',     category: 'Rice',             cal: 123, protein: 2.7, carbs: 26, fat: 0.9 },
  { id: 'jeera-rice',       name: 'Jeera Rice',              category: 'Rice',             cal: 150, protein: 3,   carbs: 30, fat: 3   },
  { id: 'veg-fried-rice-i', name: 'Veg Fried Rice (Indian)',category: 'Rice',             cal: 160, protein: 4,   carbs: 30, fat: 3.5 },
  { id: 'pulao',            name: 'Veg Pulao',               category: 'Rice',             cal: 160, protein: 4,   carbs: 28, fat: 4   },
  { id: 'khichdi',          name: 'Khichdi',                 category: 'Rice',             cal: 115, protein: 4,   carbs: 20, fat: 2.5 },
  { id: 'curd-rice',        name: 'Curd Rice',               category: 'Rice',             cal: 120, protein: 4,   carbs: 20, fat: 3   },
  { id: 'lemon-rice',       name: 'Lemon Rice',              category: 'Rice',             cal: 145, protein: 3,   carbs: 28, fat: 3   },

  // ── Dal & Lentils ─────────────────────────────────────────────────────────────
  { id: 'dal-makhani',      name: 'Dal Makhani',             category: 'Dal & Lentils',    cal: 152, protein: 7,   carbs: 18, fat: 5   },
  { id: 'dal-tadka',        name: 'Dal Tadka',               category: 'Dal & Lentils',    cal: 110, protein: 6,   carbs: 16, fat: 2.5 },
  { id: 'dal-fry',          name: 'Dal Fry',                 category: 'Dal & Lentils',    cal: 120, protein: 6,   carbs: 17, fat: 3   },
  { id: 'rajma',            name: 'Rajma Curry',             category: 'Dal & Lentils',    cal: 140, protein: 8,   carbs: 20, fat: 3.5 },
  { id: 'chole',            name: 'Chole / Chana Masala',    category: 'Dal & Lentils',    cal: 160, protein: 8,   carbs: 22, fat: 4   },
  { id: 'moong-dal',        name: 'Moong Dal (cooked)',      category: 'Dal & Lentils',    cal: 100, protein: 7,   carbs: 14, fat: 1   },
  { id: 'masoor-dal',       name: 'Masoor Dal (cooked)',     category: 'Dal & Lentils',    cal: 105, protein: 7,   carbs: 15, fat: 1.5 },
  { id: 'chana-dal',        name: 'Chana Dal (cooked)',      category: 'Dal & Lentils',    cal: 120, protein: 7,   carbs: 18, fat: 2   },
  { id: 'toor-dal',         name: 'Toor Dal (cooked)',       category: 'Dal & Lentils',    cal: 105, protein: 6.5, carbs: 16, fat: 1.5 },
  { id: 'urad-dal',         name: 'Urad Dal (cooked)',       category: 'Dal & Lentils',    cal: 115, protein: 7.5, carbs: 16, fat: 1.5 },
  { id: 'chana-saag',       name: 'Chana Saag',              category: 'Dal & Lentils',    cal: 140, protein: 7,   carbs: 18, fat: 4   },

  // ── Paneer ───────────────────────────────────────────────────────────────────
  { id: 'raw-paneer',       name: 'Paneer (raw)',            category: 'Paneer',           cal: 265, protein: 18,  carbs: 2,  fat: 21  },
  { id: 'paneer-butter',    name: 'Paneer Butter Masala',    category: 'Paneer',           cal: 210, protein: 10,  carbs: 8,  fat: 16  },
  { id: 'palak-paneer',     name: 'Palak Paneer',            category: 'Paneer',           cal: 175, protein: 10,  carbs: 7,  fat: 13  },
  { id: 'paneer-tikka',     name: 'Paneer Tikka',            category: 'Paneer',           cal: 265, protein: 18,  carbs: 8,  fat: 18  },
  { id: 'kadai-paneer',     name: 'Kadai Paneer',            category: 'Paneer',           cal: 220, protein: 11,  carbs: 9,  fat: 17  },
  { id: 'paneer-bhurji',    name: 'Paneer Bhurji',           category: 'Paneer',           cal: 230, protein: 13,  carbs: 7,  fat: 17  },
  { id: 'shahi-paneer',     name: 'Shahi Paneer',            category: 'Paneer',           cal: 245, protein: 10,  carbs: 10, fat: 19  },
  { id: 'matar-paneer',     name: 'Matar Paneer',            category: 'Paneer',           cal: 185, protein: 9,   carbs: 12, fat: 12  },
  { id: 'paneer-tikka-masala', name: 'Paneer Tikka Masala', category: 'Paneer',           cal: 225, protein: 13,  carbs: 9,  fat: 16  },
  { id: 'paneer-kofta',     name: 'Paneer Kofta Curry',      category: 'Paneer',           cal: 255, protein: 10,  carbs: 14, fat: 18  },

  // ── Chicken ──────────────────────────────────────────────────────────────────
  { id: 'grilled-chicken',  name: 'Grilled Chicken Breast',  category: 'Chicken',          cal: 165, protein: 31,  carbs: 0,  fat: 3.6 },
  { id: 'butter-chicken',   name: 'Butter Chicken',          category: 'Chicken',          cal: 195, protein: 16,  carbs: 8,  fat: 11  },
  { id: 'chicken-tikka-masala', name: 'Chicken Tikka Masala',category: 'Chicken',          cal: 165, protein: 15,  carbs: 8,  fat: 8   },
  { id: 'chicken-tikka',    name: 'Chicken Tikka',           category: 'Chicken',          cal: 180, protein: 25,  carbs: 4,  fat: 7   },
  { id: 'tandoori-chicken', name: 'Tandoori Chicken',        category: 'Chicken',          cal: 175, protein: 23,  carbs: 4,  fat: 7   },
  { id: 'chicken-curry',    name: 'Chicken Curry',           category: 'Chicken',          cal: 155, protein: 15,  carbs: 5,  fat: 8   },
  { id: 'chicken-biryani',  name: 'Chicken Biryani',         category: 'Chicken',          cal: 185, protein: 11,  carbs: 22, fat: 6   },
  { id: 'chicken-65',       name: 'Chicken 65',              category: 'Chicken',          cal: 250, protein: 20,  carbs: 12, fat: 13  },
  { id: 'chicken-keema',    name: 'Chicken Keema',           category: 'Chicken',          cal: 195, protein: 18,  carbs: 6,  fat: 11  },
  { id: 'chicken-lollipop', name: 'Chicken Lollipop',        category: 'Chicken',          cal: 220, protein: 17,  carbs: 10, fat: 13, serving: { weight: 40, label: 'piece' } },
  { id: 'chicken-korma',    name: 'Chicken Korma',           category: 'Chicken',          cal: 210, protein: 16,  carbs: 7,  fat: 14  },

  // ── Mutton / Lamb ─────────────────────────────────────────────────────────────
  { id: 'mutton-curry',     name: 'Mutton Curry',            category: 'Mutton',           cal: 235, protein: 20,  carbs: 3,  fat: 15  },
  { id: 'mutton-biryani',   name: 'Mutton Biryani',          category: 'Mutton',           cal: 210, protein: 13,  carbs: 22, fat: 7   },
  { id: 'seekh-kebab',      name: 'Seekh Kebab',             category: 'Mutton',           cal: 270, protein: 22,  carbs: 8,  fat: 17, serving: { weight: 60, label: 'piece' } },
  { id: 'mutton-rogan',     name: 'Mutton Rogan Josh',       category: 'Mutton',           cal: 245, protein: 21,  carbs: 5,  fat: 16  },
  { id: 'keema-matar',      name: 'Keema Matar',             category: 'Mutton',           cal: 220, protein: 18,  carbs: 10, fat: 13  },

  // ── Fish & Seafood ───────────────────────────────────────────────────────────
  { id: 'grilled-fish',     name: 'Grilled Fish',            category: 'Fish & Seafood',   cal: 130, protein: 22,  carbs: 0,  fat: 4   },
  { id: 'fish-curry',       name: 'Fish Curry',              category: 'Fish & Seafood',   cal: 125, protein: 16,  carbs: 4,  fat: 5   },
  { id: 'prawn-curry',      name: 'Prawn Curry',             category: 'Fish & Seafood',   cal: 120, protein: 14,  carbs: 5,  fat: 5   },
  { id: 'fish-fry',         name: 'Fish Fry (Tawa)',         category: 'Fish & Seafood',   cal: 175, protein: 20,  carbs: 5,  fat: 8   },
  { id: 'prawn-masala',     name: 'Prawn Masala',            category: 'Fish & Seafood',   cal: 130, protein: 15,  carbs: 5,  fat: 5.5 },

  // ── Biryani ──────────────────────────────────────────────────────────────────
  { id: 'veg-biryani',      name: 'Veg Biryani',             category: 'Biryani',          cal: 160, protein: 4,   carbs: 28, fat: 4   },
  { id: 'egg-biryani',      name: 'Egg Biryani',             category: 'Biryani',          cal: 175, protein: 8,   carbs: 22, fat: 6   },
  { id: 'hyderabadi-biryani',name: 'Hyderabadi Biryani',     category: 'Biryani',          cal: 195, protein: 12,  carbs: 24, fat: 6   },
  { id: 'paneer-biryani',   name: 'Paneer Biryani',          category: 'Biryani',          cal: 185, protein: 8,   carbs: 24, fat: 7   },

  // ── Vegetables ───────────────────────────────────────────────────────────────
  { id: 'aloo-matar',       name: 'Aloo Matar',              category: 'Vegetables',       cal: 95,  protein: 3,   carbs: 16, fat: 3   },
  { id: 'bhindi-masala',    name: 'Bhindi Masala',           category: 'Vegetables',       cal: 80,  protein: 2,   carbs: 12, fat: 3   },
  { id: 'baingan-bharta',   name: 'Baingan Bharta',          category: 'Vegetables',       cal: 90,  protein: 2,   carbs: 10, fat: 5   },
  { id: 'mixed-veg',        name: 'Mixed Veg Curry',         category: 'Vegetables',       cal: 85,  protein: 2.5, carbs: 12, fat: 3   },
  { id: 'aloo-gobi',        name: 'Aloo Gobi',               category: 'Vegetables',       cal: 95,  protein: 3,   carbs: 14, fat: 3.5 },
  { id: 'jeera-aloo',       name: 'Jeera Aloo',              category: 'Vegetables',       cal: 110, protein: 2,   carbs: 18, fat: 4   },
  { id: 'saag',             name: 'Saag (Sarson)',           category: 'Vegetables',       cal: 70,  protein: 4,   carbs: 8,  fat: 3   },
  { id: 'mushroom-masala',  name: 'Mushroom Masala',         category: 'Vegetables',       cal: 100, protein: 4,   carbs: 9,  fat: 5   },
  { id: 'pav-bhaji-bhaji',  name: 'Pav Bhaji (bhaji)',      category: 'Vegetables',       cal: 120, protein: 3,   carbs: 18, fat: 4.5 },
  { id: 'lauki-sabzi',      name: 'Lauki Sabzi',             category: 'Vegetables',       cal: 60,  protein: 1.5, carbs: 9,  fat: 2   },
  { id: 'matar-mushroom',   name: 'Matar Mushroom',          category: 'Vegetables',       cal: 90,  protein: 4,   carbs: 10, fat: 3.5 },

  // ── Street Food & Snacks ─────────────────────────────────────────────────────
  { id: 'samosa',           name: 'Samosa',                  category: 'Street Food',      cal: 260, protein: 5,   carbs: 30, fat: 14, serving: { weight: 100, label: 'piece'   } },
  { id: 'kachori',          name: 'Kachori',                 category: 'Street Food',      cal: 330, protein: 7,   carbs: 40, fat: 16, serving: { weight: 80,  label: 'piece'   } },
  { id: 'vada-pav',         name: 'Vada Pav',                category: 'Street Food',      cal: 220, protein: 5,   carbs: 34, fat: 8,  serving: { weight: 150, label: 'piece'   } },
  { id: 'pani-puri',        name: 'Pani Puri',               category: 'Street Food',      cal: 170, protein: 3,   carbs: 28, fat: 5,  serving: { weight: 15,  label: 'piece'   } },
  { id: 'bhel-puri',        name: 'Bhel Puri',               category: 'Street Food',      cal: 155, protein: 4,   carbs: 28, fat: 4   },
  { id: 'sev-puri',         name: 'Sev Puri',                category: 'Street Food',      cal: 230, protein: 5,   carbs: 32, fat: 10, serving: { weight: 20,  label: 'piece'   } },
  { id: 'dahi-puri',        name: 'Dahi Puri',               category: 'Street Food',      cal: 185, protein: 5,   carbs: 28, fat: 6,  serving: { weight: 25,  label: 'piece'   } },
  { id: 'pav-bhaji',        name: 'Pav Bhaji (with pav)',   category: 'Street Food',      cal: 200, protein: 5,   carbs: 32, fat: 7   },
  { id: 'veg-pakora',       name: 'Veg Pakora',              category: 'Street Food',      cal: 250, protein: 6,   carbs: 28, fat: 13, serving: { weight: 30,  label: 'piece'   } },
  { id: 'onion-pakora',     name: 'Onion Pakora',            category: 'Street Food',      cal: 255, protein: 5,   carbs: 30, fat: 13, serving: { weight: 25,  label: 'piece'   } },
  { id: 'dhokla',           name: 'Dhokla',                  category: 'Street Food',      cal: 160, protein: 5,   carbs: 28, fat: 3.5,serving: { weight: 50,  label: 'piece'   } },
  { id: 'khandvi',          name: 'Khandvi',                 category: 'Street Food',      cal: 180, protein: 7,   carbs: 22, fat: 7   },
  { id: 'dahi-vada',        name: 'Dahi Vada',               category: 'Street Food',      cal: 175, protein: 6,   carbs: 24, fat: 6,  serving: { weight: 80,  label: 'piece'   } },
  { id: 'papdi-chaat',      name: 'Papdi Chaat',             category: 'Street Food',      cal: 215, protein: 5,   carbs: 32, fat: 8   },
  { id: 'aloo-tikki',       name: 'Aloo Tikki',              category: 'Street Food',      cal: 195, protein: 4,   carbs: 30, fat: 7,  serving: { weight: 80,  label: 'piece'   } },

  // ── South Indian ─────────────────────────────────────────────────────────────
  { id: 'idli',             name: 'Idli',                    category: 'South Indian',     cal: 145, protein: 5,   carbs: 30, fat: 1,   serving: { weight: 40,  label: 'idli'    } },
  { id: 'plain-dosa',       name: 'Dosa (Plain)',            category: 'South Indian',     cal: 166, protein: 4,   carbs: 31, fat: 3.4, serving: { weight: 100, label: 'dosa'    } },
  { id: 'masala-dosa',      name: 'Masala Dosa',             category: 'South Indian',     cal: 150, protein: 4,   carbs: 28, fat: 3,   serving: { weight: 150, label: 'dosa'    } },
  { id: 'uttapam',          name: 'Uttapam',                 category: 'South Indian',     cal: 150, protein: 5,   carbs: 28, fat: 2.5, serving: { weight: 120, label: 'piece'   } },
  { id: 'sambar',           name: 'Sambar',                  category: 'South Indian',     cal: 55,  protein: 3,   carbs: 8,  fat: 1.5 },
  { id: 'coconut-chutney',  name: 'Coconut Chutney',         category: 'South Indian',     cal: 205, protein: 2,   carbs: 14, fat: 16  },
  { id: 'medu-vada',        name: 'Medu Vada',               category: 'South Indian',     cal: 310, protein: 10,  carbs: 40, fat: 14, serving: { weight: 60,  label: 'vada'    } },
  { id: 'rava-dosa',        name: 'Rava Dosa',               category: 'South Indian',     cal: 175, protein: 5,   carbs: 30, fat: 4,   serving: { weight: 100, label: 'dosa'    } },
  { id: 'set-dosa',         name: 'Set Dosa',                category: 'South Indian',     cal: 165, protein: 4.5, carbs: 30, fat: 3.5, serving: { weight: 80,  label: 'dosa'    } },
  { id: 'rasam',            name: 'Rasam',                   category: 'South Indian',     cal: 30,  protein: 1.5, carbs: 5,  fat: 0.5 },
  { id: 'appam',            name: 'Appam',                   category: 'South Indian',     cal: 155, protein: 3,   carbs: 30, fat: 2.5, serving: { weight: 60,  label: 'appam'   } },
  { id: 'puttu',            name: 'Puttu',                   category: 'South Indian',     cal: 195, protein: 4,   carbs: 42, fat: 1   },
  { id: 'ven-pongal',       name: 'Ven Pongal',              category: 'South Indian',     cal: 155, protein: 4,   carbs: 28, fat: 4   },

  // ── Indian Chinese ───────────────────────────────────────────────────────────
  { id: 'hakka-noodles-veg',    name: 'Hakka Noodles (Veg)',     category: 'Indian Chinese', cal: 165, protein: 5,   carbs: 28, fat: 4   },
  { id: 'hakka-noodles-chkn',   name: 'Hakka Noodles (Chicken)', category: 'Indian Chinese', cal: 190, protein: 11,  carbs: 26, fat: 5   },
  { id: 'fried-rice-veg',       name: 'Veg Fried Rice',          category: 'Indian Chinese', cal: 160, protein: 4,   carbs: 30, fat: 3   },
  { id: 'fried-rice-chkn',      name: 'Chicken Fried Rice',      category: 'Indian Chinese', cal: 185, protein: 10,  carbs: 28, fat: 4   },
  { id: 'veg-manchurian',       name: 'Veg Manchurian',          category: 'Indian Chinese', cal: 145, protein: 3,   carbs: 22, fat: 5,  serving: { weight: 30,  label: 'ball'    } },
  { id: 'chicken-manchurian',   name: 'Chicken Manchurian',      category: 'Indian Chinese', cal: 175, protein: 14,  carbs: 15, fat: 6,  serving: { weight: 30,  label: 'piece'   } },
  { id: 'spring-roll-veg',      name: 'Spring Roll (Veg)',       category: 'Indian Chinese', cal: 200, protein: 5,   carbs: 28, fat: 8,  serving: { weight: 60,  label: 'roll'    } },
  { id: 'chilli-chicken',       name: 'Chilli Chicken (Dry)',    category: 'Indian Chinese', cal: 220, protein: 18,  carbs: 14, fat: 10  },
  { id: 'chilli-paneer',        name: 'Chilli Paneer (Dry)',     category: 'Indian Chinese', cal: 215, protein: 12,  carbs: 16, fat: 12  },
  { id: 'momos-veg',            name: 'Momos (Veg, Steamed)',    category: 'Indian Chinese', cal: 170, protein: 6,   carbs: 28, fat: 4,  serving: { weight: 20,  label: 'momo'    } },
  { id: 'momos-chicken',        name: 'Momos (Chicken, Steamed)',category: 'Indian Chinese', cal: 175, protein: 12,  carbs: 22, fat: 4.5,serving: { weight: 20,  label: 'momo'    } },
  { id: 'crispy-corn',          name: 'Crispy Corn',             category: 'Indian Chinese', cal: 340, protein: 5,   carbs: 48, fat: 15  },
  { id: 'hot-sour-soup',        name: 'Hot & Sour Soup',         category: 'Indian Chinese', cal: 45,  protein: 2,   carbs: 7,  fat: 1   },
  { id: 'manchow-soup',         name: 'Manchow Soup',            category: 'Indian Chinese', cal: 50,  protein: 2,   carbs: 8,  fat: 1.5 },
  { id: 'chilli-garlic-noodles',name: 'Chilli Garlic Noodles',   category: 'Indian Chinese', cal: 175, protein: 5,   carbs: 29, fat: 5   },
  { id: 'american-chopsuey',    name: 'American Chopsuey',       category: 'Indian Chinese', cal: 195, protein: 6,   carbs: 32, fat: 6   },

  // ── Italian ──────────────────────────────────────────────────────────────────
  { id: 'pasta-cooked',         name: 'Pasta (Cooked, Plain)',   category: 'Italian',        cal: 131, protein: 5,   carbs: 25, fat: 1.1 },
  { id: 'pasta-arrabiata',      name: 'Pasta Arrabiata',         category: 'Italian',        cal: 155, protein: 5,   carbs: 25, fat: 4   },
  { id: 'pasta-alfredo',        name: 'Pasta Alfredo',           category: 'Italian',        cal: 220, protein: 7,   carbs: 23, fat: 11  },
  { id: 'pasta-bolognese',      name: 'Spaghetti Bolognese',     category: 'Italian',        cal: 170, protein: 10,  carbs: 20, fat: 5   },
  { id: 'pasta-pesto',          name: 'Pasta Pesto',             category: 'Italian',        cal: 245, protein: 7,   carbs: 24, fat: 13  },
  { id: 'pizza-cheese',         name: 'Pizza (Cheese)',          category: 'Italian',        cal: 266, protein: 11,  carbs: 33, fat: 10, serving: { weight: 100, label: 'slice'   } },
  { id: 'pizza-veg',            name: 'Pizza (Veg)',             category: 'Italian',        cal: 245, protein: 9,   carbs: 32, fat: 9,  serving: { weight: 100, label: 'slice'   } },
  { id: 'pizza-chicken',        name: 'Pizza (Chicken)',         category: 'Italian',        cal: 280, protein: 14,  carbs: 33, fat: 10, serving: { weight: 100, label: 'slice'   } },
  { id: 'margherita-pizza',     name: 'Margherita Pizza',        category: 'Italian',        cal: 255, protein: 10,  carbs: 32, fat: 10, serving: { weight: 100, label: 'slice'   } },
  { id: 'garlic-bread',         name: 'Garlic Bread',            category: 'Italian',        cal: 335, protein: 8,   carbs: 48, fat: 13, serving: { weight: 35,  label: 'slice'   } },
  { id: 'bruschetta',           name: 'Bruschetta',              category: 'Italian',        cal: 195, protein: 5,   carbs: 32, fat: 6,  serving: { weight: 40,  label: 'piece'   } },
  { id: 'risotto-veg',          name: 'Risotto (Veg)',           category: 'Italian',        cal: 165, protein: 4,   carbs: 28, fat: 4   },
  { id: 'lasagna',              name: 'Lasagna',                 category: 'Italian',        cal: 190, protein: 10,  carbs: 22, fat: 7   },
  { id: 'tiramisu',             name: 'Tiramisu',                category: 'Italian',        cal: 280, protein: 5,   carbs: 28, fat: 17  },

  // ── Japanese ─────────────────────────────────────────────────────────────────
  { id: 'sushi-mixed',          name: 'Sushi (per piece)',        category: 'Japanese',      cal: 150, protein: 6,   carbs: 28, fat: 1.5, serving: { weight: 20,  label: 'piece'   } },
  { id: 'california-roll',      name: 'California Roll',         category: 'Japanese',      cal: 140, protein: 5,   carbs: 28, fat: 1,   serving: { weight: 20,  label: 'piece'   } },
  { id: 'salmon-roll',          name: 'Salmon Roll',             category: 'Japanese',      cal: 165, protein: 9,   carbs: 24, fat: 4,   serving: { weight: 20,  label: 'piece'   } },
  { id: 'ramen',                name: 'Ramen',                   category: 'Japanese',      cal: 95,  protein: 5,   carbs: 13, fat: 2   },
  { id: 'miso-soup',            name: 'Miso Soup',               category: 'Japanese',      cal: 25,  protein: 2,   carbs: 3,  fat: 0.7 },
  { id: 'edamame',              name: 'Edamame',                 category: 'Japanese',      cal: 121, protein: 11,  carbs: 9,  fat: 5   },
  { id: 'gyoza-steamed',        name: 'Gyoza (Steamed)',         category: 'Japanese',      cal: 195, protein: 8,   carbs: 26, fat: 6.5, serving: { weight: 20,  label: 'piece'   } },
  { id: 'gyoza-fried',          name: 'Gyoza (Pan Fried)',       category: 'Japanese',      cal: 245, protein: 8,   carbs: 26, fat: 12,  serving: { weight: 20,  label: 'piece'   } },
  { id: 'tempura-veg',          name: 'Tempura (Veg)',           category: 'Japanese',      cal: 195, protein: 4,   carbs: 22, fat: 10, serving: { weight: 30,  label: 'piece'   } },
  { id: 'teriyaki-chicken',     name: 'Teriyaki Chicken',        category: 'Japanese',      cal: 170, protein: 22,  carbs: 8,  fat: 5   },
  { id: 'yakitori',             name: 'Yakitori',                category: 'Japanese',      cal: 185, protein: 20,  carbs: 6,  fat: 8,  serving: { weight: 30,  label: 'skewer'  } },
  { id: 'udon-noodles',         name: 'Udon Noodles (cooked)',   category: 'Japanese',      cal: 105, protein: 3.5, carbs: 22, fat: 0.5 },
  { id: 'onigiri',              name: 'Onigiri (Rice Ball)',     category: 'Japanese',      cal: 170, protein: 4,   carbs: 36, fat: 1,  serving: { weight: 100, label: 'piece'   } },

  // ── Eggs & Dairy ─────────────────────────────────────────────────────────────
  { id: 'whole-egg',            name: 'Whole Egg (boiled)',      category: 'Eggs & Dairy',  cal: 155, protein: 13,  carbs: 1.1, fat: 11, serving: { weight: 50,  label: 'egg'     } },
  { id: 'egg-white',            name: 'Egg White (boiled)',      category: 'Eggs & Dairy',  cal: 52,  protein: 11,  carbs: 0.7, fat: 0.2,serving: { weight: 30,  label: 'egg'     } },
  { id: 'egg-yolk',             name: 'Egg Yolk',                category: 'Eggs & Dairy',  cal: 322, protein: 16,  carbs: 3.6, fat: 27, serving: { weight: 20,  label: 'yolk'    } },
  { id: 'scrambled-eggs',       name: 'Scrambled Eggs',          category: 'Eggs & Dairy',  cal: 170, protein: 12,  carbs: 2,   fat: 13, serving: { weight: 50,  label: 'egg'     } },
  { id: 'omelette',             name: 'Omelette (Plain)',        category: 'Eggs & Dairy',  cal: 160, protein: 11,  carbs: 1,   fat: 12, serving: { weight: 100, label: 'omelette'} },
  { id: 'egg-bhurji',           name: 'Egg Bhurji',              category: 'Eggs & Dairy',  cal: 175, protein: 12,  carbs: 4,   fat: 12, serving: { weight: 50,  label: 'egg'     } },
  { id: 'full-fat-milk',        name: 'Full Fat Milk',           category: 'Eggs & Dairy',  cal: 61,  protein: 3.2, carbs: 4.7, fat: 3.5 },
  { id: 'toned-milk',           name: 'Toned Milk',              category: 'Eggs & Dairy',  cal: 58,  protein: 3.2, carbs: 4.7, fat: 3   },
  { id: 'skimmed-milk',         name: 'Skimmed Milk',            category: 'Eggs & Dairy',  cal: 35,  protein: 3.5, carbs: 5,   fat: 0.1 },
  { id: 'curd-dahi',            name: 'Curd / Dahi (Full Fat)',  category: 'Eggs & Dairy',  cal: 98,  protein: 3.5, carbs: 3.4, fat: 8   },
  { id: 'greek-yogurt',         name: 'Greek Yogurt',            category: 'Eggs & Dairy',  cal: 73,  protein: 9,   carbs: 4,   fat: 2   },
  { id: 'hung-curd',            name: 'Hung Curd (Chakka)',      category: 'Eggs & Dairy',  cal: 120, protein: 8,   carbs: 6,   fat: 7   },
  { id: 'ghee',                 name: 'Ghee',                    category: 'Eggs & Dairy',  cal: 900, protein: 0,   carbs: 0,   fat: 100 },
  { id: 'amul-butter',          name: 'Amul Butter',             category: 'Eggs & Dairy',  cal: 720, protein: 1,   carbs: 0,   fat: 80  },
  { id: 'cheese-slice',         name: 'Cheese Slice (Amul)',     category: 'Eggs & Dairy',  cal: 300, protein: 18,  carbs: 2,   fat: 25, serving: { weight: 20,  label: 'slice'   } },

  // ── Gym & Health Staples ─────────────────────────────────────────────────────
  { id: 'whey-protein',         name: 'Whey Protein Powder',     category: 'Gym Staples',   cal: 400, protein: 80,  carbs: 10, fat: 5,  serving: { weight: 30,  label: 'scoop'   } },
  { id: 'oats-raw',             name: 'Oats (Raw)',              category: 'Gym Staples',   cal: 389, protein: 17,  carbs: 66, fat: 7   },
  { id: 'oats-cooked',          name: 'Oats (Cooked)',           category: 'Gym Staples',   cal: 71,  protein: 2.5, carbs: 12, fat: 1.5 },
  { id: 'muesli',               name: 'Muesli',                  category: 'Gym Staples',   cal: 365, protein: 10,  carbs: 65, fat: 6   },
  { id: 'cornflakes',           name: 'Cornflakes',              category: 'Gym Staples',   cal: 357, protein: 8,   carbs: 84, fat: 0.9 },
  { id: 'brown-bread',          name: 'Brown Bread',             category: 'Gym Staples',   cal: 247, protein: 9,   carbs: 44, fat: 3.5, serving: { weight: 30,  label: 'slice'   } },
  { id: 'white-bread',          name: 'White Bread',             category: 'Gym Staples',   cal: 265, protein: 8,   carbs: 51, fat: 3,   serving: { weight: 30,  label: 'slice'   } },
  { id: 'peanut-butter',        name: 'Peanut Butter',           category: 'Gym Staples',   cal: 588, protein: 25,  carbs: 20, fat: 50  },
  { id: 'sweet-potato',         name: 'Sweet Potato (cooked)',   category: 'Gym Staples',   cal: 90,  protein: 2,   carbs: 21, fat: 0.1 },
  { id: 'quinoa-cooked',        name: 'Quinoa (cooked)',         category: 'Gym Staples',   cal: 120, protein: 4.4, carbs: 22, fat: 1.9 },
  { id: 'tofu-firm',            name: 'Tofu (Firm)',             category: 'Gym Staples',   cal: 76,  protein: 8,   carbs: 1.9, fat: 4.2 },
  { id: 'spinach',              name: 'Spinach / Palak',         category: 'Gym Staples',   cal: 23,  protein: 2.9, carbs: 3.6, fat: 0.4 },

  // ── Fruits ───────────────────────────────────────────────────────────────────
  { id: 'banana',               name: 'Banana',                  category: 'Fruits',        cal: 89,  protein: 1.1, carbs: 23, fat: 0.3, serving: { weight: 120, label: 'banana'  } },
  { id: 'apple',                name: 'Apple',                   category: 'Fruits',        cal: 52,  protein: 0.3, carbs: 14, fat: 0.2, serving: { weight: 150, label: 'apple'   } },
  { id: 'mango',                name: 'Mango',                   category: 'Fruits',        cal: 60,  protein: 0.8, carbs: 15, fat: 0.4, serving: { weight: 200, label: 'mango'   } },
  { id: 'papaya',               name: 'Papaya',                  category: 'Fruits',        cal: 43,  protein: 0.5, carbs: 11, fat: 0.3 },
  { id: 'orange',               name: 'Orange',                  category: 'Fruits',        cal: 47,  protein: 0.9, carbs: 12, fat: 0.1, serving: { weight: 130, label: 'orange'  } },
  { id: 'watermelon',           name: 'Watermelon',              category: 'Fruits',        cal: 30,  protein: 0.6, carbs: 7.6, fat: 0.2 },
  { id: 'grapes',               name: 'Grapes',                  category: 'Fruits',        cal: 69,  protein: 0.7, carbs: 18, fat: 0.2 },
  { id: 'guava',                name: 'Guava',                   category: 'Fruits',        cal: 68,  protein: 2.6, carbs: 14, fat: 1,   serving: { weight: 100, label: 'guava'   } },
  { id: 'pomegranate',          name: 'Pomegranate',             category: 'Fruits',        cal: 83,  protein: 1.7, carbs: 19, fat: 1.2 },
  { id: 'kiwi',                 name: 'Kiwi',                    category: 'Fruits',        cal: 61,  protein: 1.1, carbs: 15, fat: 0.5, serving: { weight: 70,  label: 'kiwi'    } },
  { id: 'pineapple',            name: 'Pineapple',               category: 'Fruits',        cal: 50,  protein: 0.5, carbs: 13, fat: 0.1 },
  { id: 'strawberry',           name: 'Strawberry',              category: 'Fruits',        cal: 32,  protein: 0.7, carbs: 7.7, fat: 0.3,serving: { weight: 12,  label: 'berry'   } },
  { id: 'pear',                 name: 'Pear',                    category: 'Fruits',        cal: 57,  protein: 0.4, carbs: 15, fat: 0.1, serving: { weight: 150, label: 'pear'    } },

  // ── Nuts & Seeds ─────────────────────────────────────────────────────────────
  { id: 'almonds',              name: 'Almonds',                 category: 'Nuts & Seeds',  cal: 579, protein: 21,  carbs: 22, fat: 50, serving: { weight: 1.2, label: 'almond'  } },
  { id: 'cashews',              name: 'Cashews',                 category: 'Nuts & Seeds',  cal: 553, protein: 18,  carbs: 30, fat: 44, serving: { weight: 1.5, label: 'cashew'  } },
  { id: 'walnuts',              name: 'Walnuts',                 category: 'Nuts & Seeds',  cal: 654, protein: 15,  carbs: 14, fat: 65  },
  { id: 'peanuts',              name: 'Peanuts',                 category: 'Nuts & Seeds',  cal: 567, protein: 26,  carbs: 16, fat: 49  },
  { id: 'pistachios',           name: 'Pistachios',              category: 'Nuts & Seeds',  cal: 562, protein: 20,  carbs: 28, fat: 45  },
  { id: 'chia-seeds',           name: 'Chia Seeds',              category: 'Nuts & Seeds',  cal: 486, protein: 17,  carbs: 42, fat: 31  },
  { id: 'flaxseeds',            name: 'Flaxseeds',               category: 'Nuts & Seeds',  cal: 534, protein: 18,  carbs: 29, fat: 42  },
  { id: 'peanut-butter',        name: 'Peanut Butter',           category: 'Gym Staples',   cal: 588, protein: 25,  carbs: 20, fat: 50  },

  // ── Desserts ─────────────────────────────────────────────────────────────────
  { id: 'gulab-jamun',          name: 'Gulab Jamun',             category: 'Desserts',      cal: 175, protein: 3,   carbs: 28, fat: 6,  serving: { weight: 50,  label: 'piece'   } },
  { id: 'rasgulla',             name: 'Rasgulla',                category: 'Desserts',      cal: 110, protein: 3,   carbs: 22, fat: 1,  serving: { weight: 80,  label: 'piece'   } },
  { id: 'gajar-halwa',          name: 'Gajar Halwa',             category: 'Desserts',      cal: 210, protein: 4,   carbs: 32, fat: 8   },
  { id: 'kheer',                name: 'Kheer',                   category: 'Desserts',      cal: 150, protein: 4,   carbs: 24, fat: 5   },
  { id: 'jalebi',               name: 'Jalebi',                  category: 'Desserts',      cal: 358, protein: 3,   carbs: 72, fat: 7,  serving: { weight: 30,  label: 'piece'   } },
  { id: 'barfi-milk',           name: 'Milk Barfi',              category: 'Desserts',      cal: 345, protein: 8,   carbs: 55, fat: 10, serving: { weight: 40,  label: 'piece'   } },
  { id: 'ice-cream-vanilla',    name: 'Ice Cream (Vanilla)',     category: 'Desserts',      cal: 207, protein: 3.5, carbs: 24, fat: 11  },
  { id: 'chocolate',            name: 'Dark Chocolate (70%)',    category: 'Desserts',      cal: 598, protein: 8,   carbs: 46, fat: 43  },

  // ── Beverages ────────────────────────────────────────────────────────────────
  { id: 'masala-chai',          name: 'Masala Chai (with milk)', category: 'Beverages',     cal: 55,  protein: 2,   carbs: 7,  fat: 2   },
  { id: 'black-coffee',         name: 'Black Coffee',            category: 'Beverages',     cal: 2,   protein: 0.3, carbs: 0,  fat: 0   },
  { id: 'protein-shake',        name: 'Protein Shake (made up)', category: 'Beverages',     cal: 160, protein: 28,  carbs: 8,  fat: 2   },
  { id: 'lassi-sweet',          name: 'Lassi (Sweet)',           category: 'Beverages',     cal: 110, protein: 3.5, carbs: 18, fat: 3   },
  { id: 'lassi-salted',         name: 'Lassi (Salted)',          category: 'Beverages',     cal: 65,  protein: 3.5, carbs: 5,  fat: 3   },
  { id: 'mango-lassi',          name: 'Mango Lassi',             category: 'Beverages',     cal: 115, protein: 3,   carbs: 20, fat: 2.5 },
  { id: 'buttermilk',           name: 'Buttermilk / Chaas',      category: 'Beverages',     cal: 40,  protein: 3,   carbs: 5,  fat: 1   },
  { id: 'coconut-water',        name: 'Coconut Water',           category: 'Beverages',     cal: 19,  protein: 0.7, carbs: 3.7, fat: 0.2 },
  { id: 'orange-juice',         name: 'Orange Juice (fresh)',    category: 'Beverages',     cal: 45,  protein: 0.7, carbs: 10, fat: 0.2 },
]
